del istartup.a
del istartup.b
del istartup.cpp
del wcon.a
del wcon.s
del iprofile.a
del iprofile.b
del ifileIO3.a
del ifileIO3_.s
del wfileIO3.a
del wfileIO3.s
del _startup1.s
del _startup2.s
del _startup1.go
del itrace.a
del itrace.b
del wcon_imports.a
del wcon_imports.cpp
